u1 = User.create(username: "Mike", password: "testing", avatar_url: 'https://www.filepicker.io/api/file/fbcdO6dKSCGPimifqhRW')
u2 = User.create(username: "Jimmy", password: "testing")
u3 = User.create(username: "Eric", password: "testing")
u4 = User.create(username: "Rob", password: "testing")
u5 = User.create(username: "Yusuf", password: "testing", avatar_url: 'https://www.filepicker.io/api/file/FXuj2BpqTX6J7iLr4Gr4')
u6 = User.create(username: "Guest", password: "welcome")
u7 = User.create(username: "Ned", password: "testing", avatar_url: 'https://www.filepicker.io/api/file/yGuMqopiR1SfmNSULbS3')
u8 = User.create(username: "Will", password: "testing")
u9 = User.create(username: "Jeff", password: "testing")
u10 = User.create(username: "CJ", password: "testing", avatar_url: 'https://www.filepicker.io/api/file/Y64fu8SSbumFnrcXGZTo')
u11 = User.create(username: "Shawna", password: "testing")
u12 = User.create(username: "Arnold", password: "testing")

b1 = Business.create(name: "Saigon Sandwich", category: "Restaurants", price: 1, x_coord: 37.783146, y_coord: -122.417381, avatar_url: "https://www.filepicker.io/api/file/d1dvlHp4R7ygHE7iaEJF")
b2 = Business.create(name: "Philz Coffee", category: "Coffee & Tea", price: 2, x_coord: 37.781332, y_coord: -122.416737, avatar_url: "https://www.filepicker.io/api/file/H1PkC5zZQB2F1TEqvmCO")
b3 = Business.create(name: "Tropisueno", category: "Restaurants", price: 3, x_coord: 37.785394, y_coord: -122.403967, avatar_url: "https://www.filepicker.io/api/file/drIi9yUTUuSbgUazlgEI")
b4 = Business.create(name: "Elbo Room", category: "Bars & Nightlife", price: 2, x_coord: 37.762515, y_coord: -122.421513)
b5 = Business.create(name: "Showdogs", category: "Restaurants", price: 2, x_coord: 37.782118, y_coord: -122.410881)
b6 = Business.create(name: "Tempest", category: "Bars & Nightlife", price: 2, x_coord: 37.781168, y_coord: -122.406289)
b7 = Business.create(name: "In-N-Out", category: "Restaurants", price: 1, x_coord: 37.807718, y_coord: -122.418551, avatar_url: "https://www.filepicker.io/api/file/SHzn1IM8RacawQMgfjgn")
b8 = Business.create(name: "Giant Monkey Movers", category: "Home Services", price: 4, x_coord: 37.782897, y_coord: -122.41496, avatar_url: "https://www.filepicker.io/api/file/C52K5uTMQTiJlRFujA3s")
b9 = Business.create(name: "Friendly Plumber", category: "Home Services", price: 1, x_coord: 37.772829, y_coord: -122.483263)
b10 = Business.create(name: "Happy Donut", category: "Bakeries", price: 1, x_coord: 37.791561, y_coord: -122.399799)
b11 = Business.create(name: "Little Sheep Hot Pot", category: "Restaurants", price: 3, x_coord: 37.787296, y_coord: -122.410178, avatar_url: "https://www.filepicker.io/api/file/HLWhx4rZTB6VejwHPl1I")
b12 = Business.create(name: "Batter Bakery", category: "Bakeries", price: 1, x_coord: 37.792181, y_coord: -122.404035)
b13 = Business.create(name: "Noc Noc", category: "Bars & Nightlife", price: 2, x_coord: 37.771849, y_coord: -122.4314)
b14 = Business.create(name: "Split Bread", category: "Restaurants", price: 2, x_coord: 37.784118, y_coord: -122.403561)
b15 = Business.create(name: "SFMOMA", category: "Arts & Entertainment", price: 1, x_coord: 37.7856560, y_coord: -122.4012520)
b16 = Business.create(name: "Oolong Noodles Restaurant", category: "Restaurants", price: 3, x_coord: 37.795618, y_coord: -122.40437)
b17 = Business.create(name: "Señor Sisig", category: "Food Carts", price: 1, x_coord: 37.787584, y_coord: -122.399611, avatar_url: "https://www.filepicker.io/api/file/UZVDNbKGQLauwNyVur6O")
b18 = Business.create(name: "Blue Cross Pet Hospital", category: "Health & Medical", price: 1, x_coord: 37.779627, y_coord: -122.433349, avatar_url: "https://www.filepicker.io/api/file/bEGvoFYYTkyrbpCwamK4")
b19 = Business.create(name: "Tu Lan Vietnamese Restaurant", category: "Restaurants", price: 1, x_coord: 37.781861, y_coord: -122.410144, avatar_url: "https://www.filepicker.io/api/file/56lMrW5Qp2DCoEiKrhB8")
b20 = Business.create(name: "Brenda's", category: "Restaurants", price: 2, x_coord: 37.78292, y_coord: -122.418971)
b21 = Business.create(name: "Yerba Buena Gardens", category: "Arts & Entertainment", price: 1, x_coord: 37.785094, y_coord: -122.40274)
b22 = Business.create(name: "Westfield San Francisco Centre", category: "Shopping", price: 2, x_coord: 37.784143, y_coord: -122.407361)
b23 = Business.create(name: "24 Hour Fitness", category: "Gyms", price: 1, x_coord: 37.725616, y_coord: -122.462063)
b24 = Business.create(name: "Asian Art Museum", category: "Arts & Entertainment", price: 1, x_coord: 37.780264, y_coord: -122.416384)
b25 = Business.create(name: "Circle Community Acupuncture", category: "Health & Medical", price: 3, x_coord: 37.771866, y_coord: -122.410616)
b26 = Business.create(name: "Benkyodo Co", category: "Bakeries", price: 2, x_coord: 37.786357, y_coord: -122.430161)
b27 = Business.create(name: "LaLanne Fitness", category: "Gyms", price: 3, x_coord: 37.780706, y_coord: -122.406499)

r1 = Review.create(content: "This place is da bomb. Would definitely come here for lunch every day.", stars: 5, user_id: 1, business_id: 1, go_again: true)
r2 = Review.create(content: "I think someone spit in my food, but I have no proof...", stars: 1, user_id: 3, business_id: 1, go_again: true)
	r2.toggle!(:go_again)
r3 = Review.create(content: "I feel neutral about this experience. Had better and have definitely had worse.", stars: 3, user_id: 4, business_id: 1, go_again: true)
r4 = Review.create(content: "Eh...", stars: 2, user_id: 5, business_id: 1, go_again: true)
	r4.toggle!(:go_again)
r5 = Review.create(content: "Mmmm coffee. Drink down all the good stuff they have here.", stars: 5, user_id: 3, business_id: 2, go_again: true)
r6 = Review.create(content: "Good vibe, cheap beer. What else could you ask for?", stars: 4, user_id: 1, business_id: 4, go_again: true)
r7 = Review.create(content: "These guys were pretty good. I felt like the price was fair and they were done quickly. My guy's name was Matt, he was an upstanding gentleman.", stars: 4, user_id: 1, business_id: 9, go_again: true)
r8 = Review.create(content: "I think I may have got food poisoning from the wonton soup", stars: 1, user_id: 7, business_id: 16, go_again: true)
	r8.toggle!(:go_again)
r9 = Review.create(content: "Overrated. Still pretty good though", stars: 4, user_id: 7, business_id: 13, go_again: true)
r10 = Review.create(content: "The sandwiches are tasty, and the price is good. My favorite is the pork.", stars: 5, user_id: 11, business_id: 1, go_again: true)
r11 = Review.create(content: "Everyone should go here at least once - it's so tasty", stars: 4, user_id: 9, business_id: 1, go_again: true)
r12 = Review.create(content: "Too crowded, the beer was only average", stars: 2, user_id: 10, business_id: 13, go_again: true)
	r12.toggle!(:go_again)
r13 = Review.create(content: "I like art, and this place has it.", stars: 4, user_id: 1, business_id: 15, go_again: true)
r14 = Review.create(content: "Oh yes, burrito", stars: 4, user_id: 10, business_id: 3, go_again: true)
r15 = Review.create(content: "Fajitas all day and all night", stars: 4, user_id: 11, business_id: 3, go_again: true)
r16 = Review.create(content: "I like margaritas more than I care to admit", stars: 5, user_id: 5, business_id: 3, go_again: true)
r17 = Review.create(content: "Very good.", stars: 5, user_id: 1, business_id: 17, go_again: true)
r18 = Review.create(content: "They close way, way too early", stars: 1, user_id: 7, business_id: 19, go_again: true)
	r18.toggle!(:go_again)
r19 = Review.create(content: "I like it animal style", stars: 4, user_id: 1, business_id: 7, go_again: true)
r20 = Review.create(content: "I like it animal style", stars: 4, user_id: 1, business_id: 18, go_again: true)
r21 = Review.create(content: "Combo platter!!!", stars: 5, user_id: 3, business_id: 11, go_again: true)
r22 = Review.create(content: "Spicy broth is win", stars: 4, user_id: 4, business_id: 11, go_again: true)
r23 = Review.create(content: "Really liked the new exhibit", stars: 2, user_id: 11, business_id: 15, go_again: true)
	r23.toggle!(:go_again)
r24 = Review.create(content: "Ah yes, many great times", stars: 4, user_id: 2, business_id: 14, go_again: true)
r25 = Review.create(content: "Oh no, bad times", stars: 2, user_id: 2, business_id: 19, go_again: true)
	r25.toggle!(:go_again)
r26 = Review.create(content: "Hunger is over", stars: 5, user_id: 9, business_id: 17, go_again: true)
r27 = Review.create(content: "I believe this is the best bakery of all time", stars: 5, user_id: 9, business_id: 12, go_again: true)
r28 = Review.create(content: "The Poboy is delicious would eat again", stars: 5, user_id: 10, business_id: 20, go_again: true)
r29 = Review.create(content: "I like my burger when it's on fire", stars: 4, user_id: 2, business_id: 7, go_again: true)
r30 = Review.create(content: "This is the real deal. Will definitely come back here for snacks.", stars: 5, user_id: 1, business_id: 26, go_again: true)
r31 = Review.create(content: "My cat Markov is all better after taking him here! No complaints, everything was great.", stars: 5, user_id: 7, business_id: 18, go_again: true)
r32 = Review.create(content: "The wait was not insignificant, and the food itself did not live up to the hype.", stars: 3, user_id: 8, business_id: 20, go_again: true)
	r32.toggle!(:go_again)
r33 = Review.create(content: "A bit overpriced. The maple dog was good though.", stars: 3, user_id: 6, business_id: 5, go_again: true)
r34 = Review.create(content: "It was a little shabby, don't know if I'll come back here.", stars: 2, user_id: 8, business_id: 24, go_again: true)
	r34.toggle!(:go_again)
r35 = Review.create(content: "How swole is too swole? That's a trick question.", stars: 4, user_id: 12, business_id: 27, go_again: true)
r36 = Review.create(content: "Work out yeah", stars: 3, user_id: 4, business_id: 27, go_again: true)
r37 = Review.create(content: "I like chilling out here on the weekends", stars: 5, user_id: 9, business_id: 21, go_again: true)


p1 = Photo.create(fp_url: "https://www.filepicker.io/api/file/6UBDkLpR3WUEeOKbVAA3", review_id: 1)
p2 = Photo.create(fp_url: "https://www.filepicker.io/api/file/HVnGlto1T7KlR0ToymXW", review_id: 6)
p3 = Photo.create(fp_url: "https://www.filepicker.io/api/file/9dH29uYIQXOuatkRZrWH", review_id: 28)
p4 = Photo.create(fp_url: "https://www.filepicker.io/api/file/gb9t4yjNRWHDPGgdlm7g", review_id: 29)
p5 = Photo.create(fp_url: "https://www.filepicker.io/api/file/IQzsetO8TbiEKUdgZwMS", review_id: 30)
p6 = Photo.create(fp_url: "https://www.filepicker.io/api/file/43C4WatTdeOW4uOW7XMU", review_id: 3)
p7 = Photo.create(fp_url: "https://www.filepicker.io/api/file/HiZaGh9LQAG0RMhM6DCB", review_id: 14)
p8 = Photo.create(fp_url: "https://www.filepicker.io/api/file/DTEKEBYvRqK5DMC5d9rV", review_id: 31)
p9 = Photo.create(fp_url: "https://www.filepicker.io/api/file/rGz5rq4nRCC1Q5ddBpJB", review_id: 32)
p10 = Photo.create(fp_url: "https://www.filepicker.io/api/file/Z3Sf8mmkTDOE76I72yC6", review_id: 33)
p11 = Photo.create(fp_url: "https://www.filepicker.io/api/file/r4YDKyY4QHGNhzR8UOCV", review_id: 34)
p12 = Photo.create(fp_url: "https://www.filepicker.io/api/file/0phXkTGOQhGCHGXUaoNc", review_id: 9)
p13 = Photo.create(fp_url: "https://www.filepicker.io/api/file/iFoj2lHmT7aHkLeC8ql7", review_id: 35)
p14 = Photo.create(fp_url: "https://www.filepicker.io/api/file/rPl1sJrRcCvQAf2riI0n", review_id: 36)
p15 = Photo.create(fp_url: "https://www.filepicker.io/api/file/jEDWpGMTbunl46widBqp", review_id: 37)